[project]
name = "fxptt"
version = "0.1.0"
description = "修復 PTT 在 Discord 上的連結預覽"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.14",
    "beautifulsoup4>=4.13.4",
    "fastapi>=0.116.1",
    "lxml>=6.0.0",
    "python-dotenv>=1.1.1",
    "uvicorn>=0.35.0",
]
